import importlib
import os

env_config = os.getenv('CSLT_ENV', 'local').lower()

ENV = importlib.import_module('.' + env_config, 'envs')

MYSQL_HOST = os.getenv('CSLT_DB_HOST', ENV.MYSQL_HOST)
MYSQL_DBNAME = os.getenv('CSLT_DB_NAME', ENV.MYSQL_DBNAME)
MYSQL_USER = os.getenv('CSLT_DB_USER', ENV.MYSQL_USER)
MYSQL_PWD = os.getenv('CSLT_DB_PASS', ENV.MYSQL_PWD)
SECRET_KEY = os.getenv('CSLT_SECRET_KEY', ENV.SECRET_KEY)
TARGET_TRAINING_VIDEO_COUNT_PER_GLOSS = int(os.getenv('CSLT_TARGET_TRAINING_COUNT',
                                                  ENV.TARGET_TRAINING_COUNT))
PENDING_APPROVAL_VIDEO_LIMIT_PER_USER = int(os.getenv('CSLT_PENDING_APPROVAL_LIMIT',
                                                  ENV.PENDING_APPROVAL_LIMIT))
REVIEW_MINIMUM_TURNOUT = int(os.getenv('CSLT_MINIMUM_REVIEWS', ENV.MINIMUM_REVIEWS))
ONE_GLOSS_RECORDING_LIMIT = int(os.getenv('ONE_GLOSS_RECORDING_LIMIT', ENV.ONE_GLOSS_RECORDING_LIMIT))

STATIC_URL = ENV.STATIC_URL
MEDIA_ROOT = ENV.MEDIA_ROOT
MEDIA_URL = ENV.MEDIA_URL
SIMPLE_JWT_ACCESS_TOKEN_LIFETIME = ENV.SIMPLE_JWT_ACCESS_TOKEN_LIFETIME
SIMPLE_JWT_REFRESH_TOKEN_LIFETIME = ENV.SIMPLE_JWT_REFRESH_TOKEN_LIFETIME
SIMPLE_JWT_SLIDING_TOKEN_LIFETIME = ENV.SIMPLE_JWT_SLIDING_TOKEN_LIFETIME
SIMPLE_JWT_SLIDING_TOKEN_REFRESH_LIFETIME = ENV.SIMPLE_JWT_SLIDING_TOKEN_REFRESH_LIFETIME
LOGGING = ENV.LOGGING
DEBUG = ENV.DEBUG

NO_PIC_URL = os.path.join(STATIC_URL, 'cslt/img/no_pic.png')

SAMPLE_VIDEO_USER_ID = 5

